### PR TITLE
Fix writing multiple headers with the same key

### PR DESCRIPTION
**Pull request by ThibG**
This is a rather crude patch, but it highlights the issue behind https://github.com/socketry/falcon/issues/19

### CODE REVIEW

**Comment by ioquatix** [comment]
Ah, thanks for investigating and highlighting this issue. I thought this might be part of the issue.

I think I'll see if I can fix this in `falcon` since it's a rack-specific implementation detail (using `\n` to separate multiple fields).

**Comment by ThibG** [comment]
Is it a rack-specific plementation detail though? This seems like something coming out of your Multiple MERGE_POLICY thing in http-protocol itself.

Le 1 octobre 2018 04:05:35 GMT+02:00, Samuel Williams <notifications@github.com> a écrit :
>Ah, thanks for investigating and highlighting this issue. I thought
>this might be part of the issue.
>
>I think I'll see if I can fix this in `falcon` since it's a
>rack-specific implementation detail (using `\n` to separate multiple
>fields).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/socketry/http-protocol/pull/1#issuecomment-425771926

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by ioquatix** [comment]
Yeah, this is a rack-specific way of representing multiple headers.

Essentially the following:

```http
Cookie: a=b
Cookie: x=y
```

Becomes the following in `env`:

```ruby
env['HTTP_SET_COOKIE'] = "a=b\nx=y"
```

The opposite is also true, if you return a headers hash:

```ruby
return 200, {'set-cookie' => "a=b\nx=y"}, []
```

Should generate the following headers:

```http
set-cookie: a=b
set-cookie: x=y
```

This is a rack specific transform. The `HTTP::Protocol::Headers` class is a separate concern and in the case of falcon/rack, does not affect this issue.

**Comment by ioquatix** [comment]
Fixed, see https://github.com/socketry/falcon/issues/19 for more details. Thanks for your PR. I believe it's the wrong place to solve this issue, and it only addressed one side of the problem.

**Pull request closed without merging**
